# Minimal IP profile for CoAP over UDP.
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_DNS_RESOLVER=y
CONFIG_COAP=y

# Optional footprint trimming
# CONFIG_NET_IPV6 is not set
# CONFIG_NET_TCP is not set
# CONFIG_MQTT_LIB is not set
# CONFIG_LWM2M is not set
